name: Installing Python

on: [push]

jobs:  
  build:    
    runs-on: ${{matrix.os}} # Run build on OS defined in matrix section
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest ] 
        py-version: [3.7, 3.8, 3.9 ]
        exclude: # Exclude only combinaiton of mac-12 and python version 3.9
          - os: macos-12
            py-version: 3.9
          
    steps:
    - name: Set up Python on ${{matrix.os}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.py-version}}
        